name: zwfm-liquidsoap-dabplus
services:
  liquidsoap:
    volumes:
      - ./dabplus/odr-audioenc:/bin/odr-audioenc
      - ./dabplus/sockets:/tmp/sockets
  
  metadata:
    build:
      context: .
      dockerfile: Dockerfile
      target: metadata
    volumes:
      - ./dabplus/odr-padenc:/bin/odr-padenc
      - ./dabplus/sockets:/tmp/sockets
      - ./dabplus/slides:/dabplus/slides
      - ./dabplus/dls:/dabplus/dls
    command: /bin/odr-padenc --dir=/dabplus/slides --dls=/dabplus/dls/dls.txt --output=sockets/dab_pad
    user: 10000:10001
    restart: always