name: zwfm-liquidsoap
services:
  liquidsoap:
    image: ghcr.io/oszuidwest/zwfm-liquidsoap:2.3.2-3.6.0-3.1.0
    container_name: liquidsoap
    volumes:
      - ./scripts:/scripts
      - ./audio:/audio
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - '0.0.0.0:8888:8888/udp' # SRT Input 1
      - '0.0.0.0:9999:9999/udp' # SRT Input 2
    command: /scripts/radio.liq
    restart: unless-stopped
    user: "10000:10001"
