name: zwfm-liquidsoap-dabplus
services:
  liquidsoap:
    volumes:
      - ./dabplus/odr-audioenc:/bin/odr-audioenc
      - ./dabplus/sockets:/dabplus/sockets
  
  metadata:
    image: debian:bookworm-slim
    volumes:
      - ./dabplus/odr-padenc:/bin/odr-padenc
      - ./dabplus/sockets:/dabplus/sockets
      - ./dabplus/slides:/dabplus/slides
      - ./dabplus/dls:/dabplus/dls
    command: bash -c "apt-get update && apt-get install -y libmagickwand-6.q16-6 && /bin/odr-padenc --dir=/dabplus/slides --dls=/dabplus/dls/dls.txt --output=/dabplus/sockets/dab_pad"
    restart: always